Added my instance
realaravinth/libmedium pull request #19
Opened 2023-05-25 04:18 UTC by EsmailELBoBDev2

2023-05-27 04:37 UTC, realaravinth requested changes

2023-05-27 04:37 UTC, realaravinth commented on README.md
> +| https://libmedium.esmailelbob.xyz | Canada  | OVH | [Esmail EL BoB](https://esmailelbob.xyz)
HI, thanks for the interest, but I see something else running at the mentioned hostname :sweat_smile: 

![image](https://github.com/realaravinth/libmedium/assets/33521410/24cd7b07-5776-4ad4-8e5e-aee1965b7e37)

2023-05-27 17:37 UTC, EsmailELBoBDev2 commented
Hi @realaravinth yes, I'm moving servers. it should be done today.

2023-05-28 16:49 UTC, EsmailELBoBDev2 commented
It should be up now: https://libmedium.esmailelbob.xyz/

2023-05-29 08:13 UTC, realaravinth commented
Hi, thans for the update. Merging :)

2023-05-29 08:13 UTC, merged